# Template for single LongVViT

# General input/ouput info
image_size: 224
patch_size: 32
channels: 3
frames: 32
num_classes: 174

# Spatial Transformer
spatial_args:
  dim: 512
  depth: 3
  heads: 8
  dim_head: 128
  mlp_dim: 512
  attention_window: 7
  attention_mode: sliding_chunks
  emb_dropout: 0.1
  dropout: 0.1
  pool: cls

# Temporal Transformer
temporal_args:
  dim: 512
  depth: 3
  heads: 8
  dim_head: 256
  mlp_dim: 256
  attention_window: 4
  attention_mode: sliding_chunks
  emb_dropout: 0.1
  dropout: 0.1
  pool: cls
